# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins: 	        [jekyll-paginate]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Dr Iona Gessinger
tagline:          'Phonetics'
description:      'Phonetician | Research Coordinator | UX & Speech Technology Researcher'
url:              https://ioonaa.github.io/
baseurl:          /

author:
name:           'Dr Iona Gessinger'
url:            https://ioonaa.github.io/

paginate:         5
